print('BONUS CALCULATOR -APLHA-')
print('')
earn = float(input('Digite aqui o seu salário atual: R$'))
newearn = (earn + (15/100 * earn))
print('Com o ajuste de 15%, seu novo salário passa a ser de R${:.2f}'.format(newearn))
print('')
baseprice = float(input('Digite o preço do produto sem nenhum desconto: R$'))
parc = (baseprice + (baseprice * 15/100)) / 12
parc2 = baseprice + (baseprice * 15/100)
vista = baseprice - (baseprice * 8/100)
print('Este produto ganha um desconto de 8% se pago á vista, e fica por R${:.2f}'.format(vista))
print('Também parcelamos em até 12x de R${:.2f} com 15% de juros'.format(parc))
print('O valor total parcelado é de R${}'.format(parc2))
print('_' * 100)